name: Publish Nuget Package

on:
  pull_request:
    types:
      - closed
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build and Pack
        run: |
          dotnet build Ravelaso.UiPath.Extensions/Ravelaso.UiPath.Extensions.csproj --configuration Release
          dotnet pack Ravelaso.UiPath.Extensions/Ravelaso.UiPath.Extensions.csproj --configuration Release --no-build -o .

      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: ravelaso

      - name: Publish package
        run: dotnet nuget push *.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
